name: JAVA CI/CD to AKS

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build app
        run: mvn -f app/pom.xml clean package
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to ACR (using admin credentials)
        run: |
            az acr login \
            --name ${{ secrets.ACR_NAME }} \
            --username ${{ secrets.ACR_USERNAME }} \
            --password ${{ secrets.ACR_PASSWORD }}
            
      - name: Build Docker image
        run: |
           docker build \
             -t ${{ secrets.ACR_NAME }}.azurecr.io/demo-app:latest \
             -f app/Dockerfile \
             app
             
      - name: Push Docker image to ACR
        run: |
           docker push ${{ secrets.ACR_NAME }}.azurecr.io/demo-app:latest
        

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Build Docker image (local)
      #   run: |
      #     docker build \
      #       -t demo-app:local  \
      #       -f app/Dockerfile  \
      #       app
